export const FETCH_PLAYERS__FAILURE = 'FETCH_PLAYERS__FAILURE';
export const FETCH_PLAYERS__REQUEST = 'FETCH_PLAYERS__REQUEST';
export const FETCH_PLAYERS__SUCCESS = 'FETCH_PLAYERS__SUCCESS';

export const ADD_PLAYER__FAILURE = 'ADD_PLAYER__FAILURE';
export const ADD_PLAYER__REQUEST = 'ADD_PLAYER__REQUEST';
export const ADD_PLAYER__SUCCESS = 'ADD_PLAYER__SUCCESS';

export const EDIT_PLAYER__FAILURE = 'EDIT_PLAYER__FAILURE';
export const EDIT_PLAYER__REQUEST = 'EDIT_PLAYER__REQUEST';
export const EDIT_PLAYER__SUCCESS = 'EDIT_PLAYER__SUCCESS';
